name: sentiment_decoder
description: "A speech and text emotion recognition app."
publish_to: 'none' 
version: 1.2.0

environment:
  sdk: ">=3.5.4 <4.0.0" 

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.2
  speech_to_text: ^7.0.0
  path_provider: ^2.1.5
  record: ^5.2.0
  record_platform_interface: ^1.2.0
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  file_picker: ^5.2.0
  path: ^1.8.0
  intl: ^0.18.1
  url_launcher: ^6.2.2
  provider: ^6.0.5
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - images/ 
    - assets/images/appstore.png
